steps:
  # Step 1: Set up Gradle
  - name: 'gcr.io/cloud-builders/gradle'
    id: 'Build'
    args: ['build']

  # Step 2: Perform integration tests
  - name: 'gcr.io/cloud-builders/gradle'
    id: 'Integration Tests'
    args: ['test', '--tests', '*IT']

  # Step 3: Perform unit tests
  - name: 'gcr.io/cloud-builders/gradle'

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Build'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']

  # Step 5: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Push'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

