steps:
 # Step 1: Set up Gradle
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t',
            'australia-southeast1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/weather-api:$SHORT_SHA', '.' ]

 # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  'australia-southeast1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/weather-api:$SHORT_SHA' ]


  - name: google/cloud-sdk
    args: [ 'gcloud', 'run', 'deploy', 'weather-api',
            '--image=australia-southeast1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/weather-api:$SHORT_SHA',
            '--region', 'australia-southeast1', '--platform', 'managed',
            '--allow-unauthenticated' ]
options:
  logging: CLOUD_LOGGING_ONLY  
